export const styles: { [key: string]: React.CSSProperties } = {
  container: {
    backgroundColor: '#ffffff',
    border: '1px solid #e5e7eb',
    borderRadius: '12px',
    padding: '16px 0',
    marginBottom: '16px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
  },
  header: {
    marginBottom: '12px',
    paddingBottom: '8px',
    borderBottom: '1px solid #e5e7eb',
    paddingLeft: '16px',
    paddingRight: '16px',
  },
  title: {
    margin: 0,
    fontSize: '14px',
    fontWeight: '600',
    color: '#374151',
  },
  messagesContainer: {
    maxHeight: '200px',
    overflowY: 'auto' as React.CSSProperties['overflowY'],
  },
  messageWrapper: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: '8px',
    maxWidth: '100%',
    width: '100%',
  },
  avatar: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
  avatarText: {
    color: 'white',
    fontWeight: '700',
    fontSize: '12px',
    letterSpacing: '0.5px',
  },
  messageBubble: {
    flex: 1,
    padding: '12px 16px',
    borderRadius: '16px',
    backgroundColor: '#f8fafc',
    color: '#374151',
    border: '1px solid #e5e7eb',
    width: '100%',
    maxWidth: '100%',
  },
  messageContent: {
    wordBreak: 'break-word' as React.CSSProperties['wordBreak'],
    fontSize: '14px',
    lineHeight: '1.4',
  },
  messageTime: {
    fontSize: '11px',
    color: '#6b7280',
    marginTop: '4px',
  },
};
