export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column' as const,
    height: '100vh',
    maxHeight: '600px',
    width: '100%',
    maxWidth: '400px',
    backgroundColor: '#ffffff',
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    borderRadius: '12px',
    boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 18px',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: 'white',
  },
  backButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '32px',
    height: '32px',
    borderRadius: '8px',
    border: 'none',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    color: 'white',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    backdropFilter: 'blur(10px)',
  },
  title: {
    fontSize: '16px',
    fontWeight: '700',
    color: 'white',
    margin: 0,
    letterSpacing: '-0.01em',
  },
  headerSpacer: {
    width: '32px', // Same width as back button for centering
  },
  content: {
    flex: 1,
    padding: '16px',
    overflowY: 'auto' as const,
    backgroundColor: '#fafbfc',
  },
  form: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '16px',
    height: '100%',
  },
  categoryOptions: {
    display: 'flex',
    alignItems: 'stretch',
    gap: '6px',
    padding: '2px',
    borderRadius: '999px',
    backgroundColor: '#f3f4f6',
    border: '1px solid #e5e7eb',
  },
  categoryOption: {
    position: 'relative' as const,
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '6px 10px',
    borderRadius: '999px',
    border: '1px solid transparent',
    backgroundColor: 'transparent',
    color: '#4b5563',
    fontSize: '11px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'background-color 0.2s ease, color 0.2s ease, border-color 0.2s ease, box-shadow 0.2s ease',
    letterSpacing: '-0.01em',
  },
  categoryOptionSelected: {
    borderColor: '#4c51bf',
    backgroundColor: '#ffffff',
    color: '#1f2937',
    boxShadow: '0 4px 10px rgba(76, 81, 191, 0.15)',
  },
  categoryInput: {
    position: 'absolute' as const,
    opacity: 0,
    pointerEvents: 'none' as const,
    inset: 0,
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '6px',
  },
  label: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '13px',
    fontWeight: '600',
    color: '#374151',
    marginBottom: '4px',
  },
  labelIcon: {
    color: '#6b7280',
  },
  formTextArea: {
    padding: '12px',
    border: '2px solid #e5e7eb',
    borderRadius: '10px',
    fontSize: '13px',
    fontFamily: 'inherit',
    resize: 'vertical' as const,
    outline: 'none',
    transition: 'all 0.2s ease',
    backgroundColor: '#ffffff',
    color: '#374151',
    lineHeight: '1.5',
    minHeight: '120px',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.02)',
  },
  formInput: {
    padding: '10px 14px',
    border: '2px solid #e5e7eb',
    borderRadius: '10px',
    fontSize: '13px',
    fontFamily: 'inherit',
    outline: 'none',
    transition: 'all 0.2s ease',
    backgroundColor: '#ffffff',
    color: '#374151',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.02)',
  },
  formInputError: {
    borderColor: '#ef4444',
    backgroundColor: '#fef2f2',
  },
  errorMessage: {
    fontSize: '12px',
    color: '#ef4444',
    fontWeight: '500',
    marginTop: '4px',
  },
  formActions: {
    display: 'flex',
    gap: '8px',
    justifyContent: 'flex-end',
    paddingTop: '12px',
    marginTop: 'auto',
  },
  cancelButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '10px 16px',
    backgroundColor: '#f3f4f6',
    color: '#6b7280',
    border: '2px solid #e5e7eb',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    minWidth: '90px',
  },
  submitButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '10px 18px',
    background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    color: 'white',
    border: '2px solid transparent',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    minWidth: '110px',
  },
  errorAlert: {
    padding: '12px 16px',
    backgroundColor: '#fef2f2',
    border: '1px solid #fecaca',
    borderRadius: '8px',
    color: '#dc2626',
    fontSize: '14px',
    fontWeight: '500',
    marginBottom: '8px',
  },
  disabledButton: {
    opacity: 0.6,
    cursor: 'not-allowed',
    pointerEvents: 'none' as const,
  },
};
