export const headerStyles: { [key: string]: React.CSSProperties } = {
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    backgroundColor: '#ffffff',
    color: '#1f2937',
    borderBottom: '1px solid #f3f4f6',
    boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
  },
  userSectionWrapper: {
    position: 'relative' as React.CSSProperties['position'],
  },
  userSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 16px',
    borderRadius: '12px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    border: '1px solid transparent',
  },
  userSectionHover: {
    backgroundColor: '#f8fafc',
    borderColor: '#e2e8f0',
  },
  userIcon: {
    color: '#6366f1',
  },
  userName: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#1f2937',
  },
  chevronIcon: {
    color: '#9ca3af',
    transition: 'transform 0.2s ease',
  },
  userMenu: {
    position: 'absolute' as React.CSSProperties['position'],
    top: '100%',
    marginTop: '8px',
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
    border: '1px solid #f0f0f0',
    minWidth: '160px',
    overflow: 'hidden',
    zIndex: 50,
  },
  menuItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 16px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    color: '#374151',
    fontSize: '14px',
    fontWeight: '500',
  },
  menuItemHover: {
    backgroundColor: '#f8fafc',
    color: '#6366f1',
  },
  createButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '8px 16px',
    backgroundColor: '#6366f1',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    fontSize: '12px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 12px rgba(99, 102, 241, 0.3)',
  },
  createButtonHover: {
    backgroundColor: '#4f46e5',
    boxShadow: '0 6px 16px rgba(99, 102, 241, 0.4)',
    transform: 'translateY(-1px)',
  },
};
