export const styles: { [key: string]: React.CSSProperties } = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    width: '100%',
    maxWidth: '400px',
    backgroundColor: '#ffffff',
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    borderRadius: '12px',
    boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    backgroundColor: '#ffffff',
    color: '#1f2937',
    borderBottom: '1px solid #f3f4f6',
    boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
  },
  discussionContainer: {
    flex: 1,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    background: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)',
    position: 'relative' as React.CSSProperties['position'],
    backgroundImage: `
      radial-gradient(circle at 25% 25%, rgba(99, 102, 241, 0.05) 0%, transparent 50%),
      radial-gradient(circle at 75% 75%, rgba(6, 182, 212, 0.05) 0%, transparent 50%)
    `,
  },
  messagesArea: {
    flex: 1,
    overflowY: 'auto' as React.CSSProperties['overflowY'],
    padding: '20px 16px',
    background: 'transparent',
    position: 'relative' as React.CSSProperties['position'],
  },
  messagesWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    maxWidth: '900px',
    margin: '0 auto',
    width: '100%',
  },
  messageWrapper: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: '12px',
    maxWidth: '100%',
    animation: 'slideIn 0.3s ease-out',
  },
  messageWrapperAI: {
    alignSelf: 'flex-start',
    marginLeft: '0',
    marginRight: 'auto',
    animation: 'slideInLeft 0.3s ease-out',
    width: '100%',
  },
  messageWrapperUser: {
    alignSelf: 'flex-end',
    marginLeft: 'auto',
    marginRight: '0',
    animation: 'slideInRight 0.3s ease-out',
  },
  avatar: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
    position: 'relative' as React.CSSProperties['position'],
    overflow: 'hidden',
    border: '2px solid rgba(255, 255, 255, 0.8)',
  },
  avatarAI: {
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
  avatarUser: {
    background: 'linear-gradient(135deg, #06b6d4 0%, #0891b2 100%)',
  },
  avatarText: {
    color: 'white',
    fontWeight: '700',
    fontSize: '11px',
    letterSpacing: '0.5px',
    textShadow: '0 1px 2px rgba(0, 0, 0, 0.2)',
  },
  messageBubble: {
    padding: '14px 18px',
    borderRadius: '18px',
    maxWidth: '100%',
    width: '100%',
    position: 'relative' as React.CSSProperties['position'],
    fontSize: '14px',
    lineHeight: '1.5',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.08)',
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  aiBubble: {
    backgroundColor: 'rgba(255, 255, 255, 0.98)',
    borderBottomLeftRadius: '4px',
    color: '#1f2937',
    border: '1px solid rgba(229, 231, 235, 0.8)',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.04)',
  },
  userBubble: {
    background: 'linear-gradient(135deg, #06b6d4 0%, #0891b2 100%)',
    color: 'white',
    borderBottomRightRadius: '4px',
    border: '1px solid rgba(6, 182, 212, 0.3)',
    boxShadow: '0 2px 8px rgba(6, 182, 212, 0.2)',
  },
  messageContent: {
    wordBreak: 'break-word' as React.CSSProperties['wordBreak'],
    fontWeight: '400',
    letterSpacing: '0.01em',
    fontSize: '13px',
  },
  messageTime: {
    fontSize: '11px',
    opacity: 0.6,
    marginTop: '6px',
    fontWeight: '500',
    letterSpacing: '0.02em',
  },
  messageTimeAI: {
    textAlign: 'left',
    color: '#9ca3af',
  },
  messageTimeUser: {
    textAlign: 'right',
    color: 'rgba(255, 255, 255, 0.85)',
  },
  inputContainer: {
    padding: '16px 20px',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderTop: '1px solid rgba(229, 231, 235, 0.6)',
    backdropFilter: 'blur(20px)',
    boxShadow: '0 -4px 20px rgba(0, 0, 0, 0.08)',
  },
  inputWrapper: {
    position: 'relative' as React.CSSProperties['position'],
    display: 'flex',
    alignItems: 'flex-end',
    gap: '12px',
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: '20px',
    padding: '12px 16px',
    border: '2px solid rgba(229, 231, 235, 0.5)',
    transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    backdropFilter: 'blur(10px)',
    boxShadow: '0 4px 16px rgba(0, 0, 0, 0.08)',
  },
  inputWrapperFocus: {
    borderColor: 'rgba(99, 102, 241, 0.4)',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    boxShadow: '0 8px 32px rgba(99, 102, 241, 0.15)',
  },
  textArea: {
    flex: 1,
    border: 'none',
    backgroundColor: 'transparent',
    resize: 'none' as React.CSSProperties['resize'],
    outline: 'none',
    padding: '8px 0',
    fontFamily: 'inherit',
    fontSize: '14px',
    lineHeight: '1.4',
    maxHeight: '100px',
    color: '#1f2937',
    fontWeight: '400',
    letterSpacing: '0.01em',
  },
  sendButton: {
    display: 'grid',
    alignItems: 'center',
    justifyContent: 'center',
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    border: '2px solid transparent',
    backgroundColor: 'rgba(229, 231, 235, 0.8)',
    color: '#9ca3af',
    cursor: 'pointer',
    transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    backdropFilter: 'blur(10px)',
  },
  sendButtonActive: {
    background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    color: 'white',
    borderColor: 'rgba(139, 92, 246, 0.3)',
    boxShadow: '0 8px 24px rgba(99, 102, 241, 0.4)',
    transform: 'scale(1.05)',
  },
  userSectionWrapper: {
    position: 'relative' as React.CSSProperties['position'],
  },
  userSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 16px',
    borderRadius: '12px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    border: '1px solid transparent',
  },
  userSectionHover: {
    backgroundColor: '#f8fafc',
    borderColor: '#e2e8f0',
  },
  userIcon: {
    color: '#6366f1',
  },
  userName: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#1f2937',
  },
  chevronIcon: {
    color: '#9ca3af',
    transition: 'transform 0.2s ease',
  },
  userMenu: {
    position: 'absolute' as React.CSSProperties['position'],
    top: '100%',
    marginTop: '8px',
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
    border: '1px solid #f0f0f0',
    minWidth: '160px',
    overflow: 'hidden',
    zIndex: 50,
  },
  menuItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 16px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    color: '#374151',
    fontSize: '14px',
    fontWeight: '500',
  },
  menuItemHover: {
    backgroundColor: '#f8fafc',
    color: '#6366f1',
  },
  createButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '8px 16px',
    backgroundColor: '#6366f1',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    fontSize: '12px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 12px rgba(99, 102, 241, 0.3)',
  },
  createButtonHover: {
    backgroundColor: '#4f46e5',
    boxShadow: '0 6px 16px rgba(99, 102, 241, 0.4)',
    transform: 'translateY(-1px)',
  },
  notesContainer: {
    marginTop: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  noteCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    border: '1px solid rgba(229, 231, 235, 0.6)',
    borderRadius: '12px',
    padding: '14px 18px',
    position: 'relative',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    backdropFilter: 'blur(10px)',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.06)',
  },
  noteCardHover: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderColor: 'rgba(99, 102, 241, 0.3)',
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.12)',
    transform: 'translateY(-2px)',
  },
  noteTime: {
    fontSize: '11px',
    color: '#6b7280',
    fontWeight: '500',
    marginBottom: '6px',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    letterSpacing: '0.02em',
  },
  noteContent: {
    fontSize: '13px',
    lineHeight: '1.4',
    color: '#374151',
    fontWeight: '400',
    letterSpacing: '0.01em',
  },
  noteCardIcon: {
    width: '16px',
    height: '16px',
    color: 'white',
  },
  noteCardButtonContainer: {
    display: 'flex',
    gap: '8px',
    marginTop: '12px',
  },
  noteCardButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    border: 'none',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
  completeButton: {
    backgroundColor: '#22c55e', // green
  },
  editButton: {
    backgroundColor: '#3b82f6', // blue
  },
  deleteButton: {
    backgroundColor: '#ef4444', // red
  },
  notesHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '16px',
    padding: '12px 0',
    borderBottom: '1px solid rgba(229, 231, 235, 0.4)',
  },
  notesTitle: {
    fontSize: '18px',
    fontWeight: '600',
    color: '#1f2937',
    letterSpacing: '0.01em',
  },
  notesCount: {
    fontSize: '12px',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: 'white',
    padding: '4px 12px',
    borderRadius: '20px',
    fontWeight: '600',
    letterSpacing: '0.02em',
    boxShadow: '0 2px 8px rgba(102, 126, 234, 0.3)',
  },
  emptyState: {
    textAlign: 'center',
    padding: '24px 12px',
    color: '#64748b',
  },
  emptyStateIcon: {
    fontSize: '48px',
    marginBottom: '12px',
    opacity: 0.3,
  },
  emptyStateText: {
    fontSize: '14px',
    lineHeight: '1.5',
  },
};
