const fontFamily =
  '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';

export const profileStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column' as const,
    height: '100vh',
    width: '100%',
    maxWidth: '400px',
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
    overflow: 'hidden',
    fontFamily,
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '20px 24px',
    background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    color: '#ffffff',
  },
  backButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    border: 'none',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    color: '#ffffff',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  title: {
    fontSize: '18px',
    fontWeight: 700,
    margin: 0,
    letterSpacing: '-0.01em',
  },
  headerSpacer: {
    width: '40px',
  },
  content: {
    flex: 1,
    padding: '24px',
    backgroundColor: '#f9fafb',
    position: 'relative' as const,
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    padding: '20px',
    boxShadow: '0 12px 25px -10px rgba(15, 23, 42, 0.25)',
    border: '1px solid #eef2ff',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '16px',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  },
  label: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#374151',
  },
  inputWrapper: {
    display: 'flex',
    alignItems: 'center',
    border: '1px solid #e5e7eb',
    borderRadius: '12px',
    backgroundColor: '#f9fafb',
    padding: '0 12px',
    gap: '8px',
  },
  inputIcon: {
    color: '#6366f1',
  },
  input: {
    flex: 1,
    border: 'none',
    background: 'transparent',
    padding: '12px 4px',
    fontSize: '15px',
    fontWeight: 500,
    outline: 'none',
    color: '#111827',
  },
  inputReadOnly: {
    color: '#6b7280',
    cursor: 'not-allowed',
  },
  inputError: {
    borderColor: '#fda4af',
    boxShadow: '0 0 0 1px rgba(248, 113, 113, 0.4)',
  },
  helperText: {
    fontSize: '12px',
    color: '#6b7280',
    margin: 0,
  },
  errorText: {
    fontSize: '12px',
    color: '#dc2626',
    margin: 0,
  },
  button: {
    marginTop: '8px',
    width: '100%',
    border: 'none',
    borderRadius: '12px',
    padding: '12px 16px',
    fontSize: '15px',
    fontWeight: 600,
    cursor: 'pointer',
    backgroundColor: '#4f46e5',
    color: '#ffffff',
    boxShadow: '0 10px 15px -5px rgba(79, 70, 229, 0.4)',
    transition: 'all 0.2s ease',
  },
  buttonDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
    boxShadow: 'none',
  },
  statusRow: {
    minHeight: '20px',
    marginTop: '4px',
  },
  statusText: {
    fontSize: '12px',
    color: '#6b7280',
    margin: 0,
  },
  statusSuccess: {
    color: '#059669',
  },
  statusError: {
    color: '#dc2626',
  },
  loadingState: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: '#4b5563',
    fontSize: '14px',
  },
};
