export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column' as const,
    height: '100vh',
    width: '100%',
    maxWidth: '400px',
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
    overflow: 'hidden',
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '20px 24px',
    background: 'linear-gradient(135deg, #4c6ef5 0%, #6c5ce7 100%)',
    color: 'white',
  },
  backButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    border: 'none',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    color: 'white',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  title: {
    fontSize: '18px',
    fontWeight: 700,
    margin: 0,
    color: 'white',
    letterSpacing: '-0.01em',
  },
  headerSpacer: {
    width: '40px',
  },
  content: {
    flex: 1,
    padding: '24px',
    backgroundColor: '#f9fafb',
    position: 'relative' as const,
  },
  section: {
    backgroundColor: 'white',
    borderRadius: '16px',
    padding: '20px',
    boxShadow: '0 10px 15px -3px rgba(15, 23, 42, 0.1), 0 4px 6px -4px rgba(15, 23, 42, 0.1)',
    border: '1px solid #eef2ff',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    marginBottom: '16px',
  },
  sectionIcon: {
    width: '44px',
    height: '44px',
    borderRadius: '12px',
    backgroundColor: '#eef2ff',
    color: '#4f46e5',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionTitle: {
    margin: 0,
    fontSize: '16px',
    fontWeight: 600,
    color: '#111827',
  },
  sectionSubtitle: {
    margin: 0,
    fontSize: '13px',
    color: '#6b7280',
  },
  toggle: {
    marginLeft: 'auto',
    width: '48px',
    height: '26px',
    borderRadius: '999px',
    backgroundColor: '#e5e7eb',
    display: 'flex',
    alignItems: 'center',
    padding: '0 3px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  toggleActive: {
    backgroundColor: '#4f46e5',
  },
  toggleDisabled: {
    opacity: 0.5,
    cursor: 'not-allowed',
  },
  toggleThumb: {
    width: '20px',
    height: '20px',
    borderRadius: '50%',
    backgroundColor: 'white',
    transition: 'transform 0.2s ease',
    transform: 'translateX(0px)',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.2)',
  },
  toggleThumbActive: {
    transform: 'translateX(20px)',
  },
  intervalWrapper: {
    marginTop: '16px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  },
  intervalLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    fontWeight: 600,
    color: '#374151',
  },
  intervalInput: {
    padding: '12px 14px',
    borderRadius: '12px',
    border: '1px solid #d1d5db',
    fontSize: '15px',
    fontWeight: 500,
    outline: 'none',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    boxShadow: '0 2px 4px rgba(15, 23, 42, 0.08)',
  },
  intervalInputDisabled: {
    backgroundColor: '#f3f4f6',
    color: '#9ca3af',
    cursor: 'not-allowed',
    boxShadow: 'none',
  },
  intervalHelper: {
    margin: 0,
    fontSize: '12px',
    color: '#6b7280',
  },
  footer: {
    marginTop: '16px',
    minHeight: '20px',
  },
  savingText: {
    fontSize: '12px',
    color: '#6b7280',
  },
  successText: {
    fontSize: '12px',
    color: '#059669',
  },
  errorText: {
    fontSize: '12px',
    color: '#dc2626',
  },
  loadingOverlay: {
    position: 'absolute' as const,
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(249, 250, 251, 0.8)',
    fontSize: '14px',
    fontWeight: 500,
    color: '#4b5563',
    borderRadius: '16px',
  },
} as const;
